language: go
go:
  - "1.10"
env:
  - DEP_VERSION="0.4.1"
before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - go get golang.org/x/tools/cmd/goimports
script:
  - dep ensure
  - make test
  - make clean
  - make
deploy:
  provider: releases
  api_key:
    secure: d9keyjceMpTULFicVqGDI+w/VWeBIPXYNKf7hwh13zo9tTXApSrYXpE193+dn3gMI6PKm/awlHtEsfg4dygPIGwoCGL2nVZoiP7rHq2sald0FiPUMJTFyJfJnzjnCfSlnMZi82thN0iNaOVjasnmB9Ae5CjPns9uYHGnXxb0421LpKJDbp7InB/AVOUBNGozeqAXnU5NGG628jp2GCOzaKdWbBBIK4uQ56H7CjTsGw8mq3CVHBC73FoPDyWpXjupR9IzAtnSfJVqU48FVbLgNQEYR1nyXzjFuAu6ZTSMt0ONfROtID1UwQ3+ELxdetzhoQUnFZKQ05CiVVULEypoaXeFBlo+GcFUCP6wh3cvNUnaLshSsAt6xZNIuQFSBQuwZoe/vs+nKvfvxEjYE8p87Y30B7QiEugN9Z4YnnPIgR1WF8MLw/b0T0RvLz6+acM3N6Y2dYrClCD9tqzWrD8mJU0a5SYB/0sCBa42CjANYTACPmLagz0tfZgqtZvg3kv4z+iiVbnFUT2ADXn9hBCdRzaH24WT+/6KYf37QNoSktW0jlcHQR7JsrLj/DZriYKW3hFAJjpXEI2sY7W3Xw0VpeMogUt11hWjK0xMFyE67b2eNN11mHpxvPOlsO5LHLAhUMICPdYk6HyFqhdjdmiH1e0y5X2XpTChW8HtIOZkHcg=
  file:
    - bin/terraform-provider-zerotier_darwin-amd64_${TRAVIS_TAG:-}.tgz
    - bin/terraform-provider-zerotier_linux-amd64_${TRAVIS_TAG:-}.tgz
    - bin/terraform-provider-zerotier_windows-amd64_${TRAVIS_TAG:-}.zip
  on:
    repo: cormacrelf/terraform-provider-zerotier
    tags: true
    all_branches: true
