language: go
go:
  - "1.12"
env:
  - GO111MODULE=on
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
script:
  - make test
  - make clean
  - make
deploy:
  provider: releases
  skip_cleanup: true
  file:
    - bin/terraform-provider-zerotier_darwin-amd64_${TRAVIS_TAG:-}.tgz
    - bin/terraform-provider-zerotier_linux-amd64_${TRAVIS_TAG:-}.tgz
    - bin/terraform-provider-zerotier_windows-amd64_${TRAVIS_TAG:-}.zip
  on:
    repo: CodeLenny/terraform-provider-zerotier
    tags: true
    all_branches: true
  api_key:
    secure: pXJJakJPAddPluPe2uKBDXSY7AAKZEd0DFyXsnqWCAvGT/3+C8SVK0WbK9lJ8KVvVptLnmWYKHqqloc+Dbu8pq/kbSGFVaSC8urguU/k1HttZbT/vdc5ipiR69JrHKP2DdH2WCv8WQLTUgNEvGB8FE2DA6g5WnK4iQOhXVOHms7m7AsECAoBc8cpklh97Xm5xBpKrVlPAuFjAzgOMyfkTFMGOlMWuXi7B5m3hPlQ/HG8SxDeXYIoQnI3IvpxKOkEixiye7Lz+JN8IGcixTj9Unwwzd9Mojzd5s9TCx/RZAzUAsHZpnKH7KEzBXy1agJceGJjxSbIkwDGEJBN1ALMjhaS7o8kKbx3WL0gqhmq7IvcKBYrfoMtZUt5XfD4SHTKpyaptsmYWyd39jfjQTJP22oHghbbMjbQTJ5L8SP+i2xr+FVIfXeuQF00n+44/XXjYEIxCnwu5p9kiz+Xzpvcge6FHqWz0x46cjkqC5FgrL1dCP6Q0oWm8yAaW+45YhWhR/WfHYNBZhJc1X3ydBsGh7sg0mXo8n7nwO1EIb9tazkFo5DJwSp5ECW63JXtzLRFvflqyO0VLGcBQQx3Mqh55j2K9eLZYUn5FappNJZ3FcGJTmKOJvYNbdtuW17MgqB5RmrVATCbgbSOaS/wZ18MbBDYXB05G7Mhxqmb4EaUgmo=
